# Generated by Django 5.0.7 on 2024-07-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_materials_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
